import { createServerClient } from '@/lib/supabase/server'
import { getReporterCallBySlug } from '@bipi/db'

export const dynamic = 'force-dynamic'

export async function GET(_req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const db = createServerClient()
  const report = await getReporterCallBySlug(db, slug)

  if (!report) {
    return new Response('# 404 — Report Not Found\n', { status: 404, headers: { 'Content-Type': 'text/markdown; charset=utf-8' } })
  }

  const canonicalUrl = `https://bipinews.com/reports/${report.slug}`
  const createdDate = new Date(report.created_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })

  let md = `---
title: "${(report.report_headline ?? 'Report').replace(/"/g, '\\"')}"
canonical: ${canonicalUrl}
category: ${report.report_category ?? 'News'}
published: ${report.created_at}
source: Bipi News
---

# ${report.report_headline ?? 'Report'}

**Category:** ${report.report_category ?? 'News'}
**Published:** ${createdDate}
**Source:** [Bipi News](${canonicalUrl})

---

`

  if (report.call_summary) {
    md += `## Summary\n\n${report.call_summary}\n\n`
  }

  if (report.transcript) {
    md += `## Full Report\n\n${report.transcript}\n\n`
  }

  // Sources
  const sources = (report as unknown as Record<string, unknown>).sources_json as Array<{ url?: string; title?: string }> | null
  if (sources?.length) {
    md += `## Sources\n\n`
    for (const [i, src] of sources.entries()) {
      if (src.url) {
        md += `${i + 1}. [${src.title ?? src.url}](${src.url})\n`
      }
    }
    md += '\n'
  }

  if (report.key_entities) {
    md += `## Key Entities\n\n${report.key_entities}\n\n`
  }

  md += `---\n\n*This report was generated by [Bipi News](https://bipinews.com). Read the full version at [${canonicalUrl}](${canonicalUrl}).*\n`

  return new Response(md, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Link': `<${canonicalUrl}>; rel="canonical"`,
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
      'X-Robots-Tag': 'noindex',
    },
  })
}
