export { getSupabaseClient, createSupabaseClient } from './client'
export * from './queries/agents'
export type { AgentWithDebateCount } from './queries/agents'
export * from './queries/debates'
export * from './queries/evolution'
export * from './queries/audience'
export * from './queries/fact-checks'
export * from './queries/playlists'
export * from './queries/tournaments'
export * from './utils/slugs'
