import { createServerClient } from '@/lib/supabase/server'
import { getReportBySlug } from '@bipi/db'

export const dynamic = 'force-dynamic'

export async function GET(_req: Request, { params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const db = createServerClient()
  const report = await getReportBySlug(db, slug)

  if (!report) {
    return new Response('# 404 — Article Not Found\n', { status: 404, headers: { 'Content-Type': 'text/markdown; charset=utf-8' } })
  }

  const canonicalUrl = `https://bipinews.com/news/${report.slug}`
  const publishedDate = report.published_at
    ? new Date(report.published_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : ''

  let md = `---
title: "${report.headline.replace(/"/g, '\\"')}"
canonical: ${canonicalUrl}
category: ${report.category}
published: ${report.published_at ?? report.created_at}
source: Bipi News
---

# ${report.headline}

${report.subheadline ? `*${report.subheadline}*\n` : ''}
**Category:** ${report.category}
**Published:** ${publishedDate}
**Source:** [Bipi News](${canonicalUrl})

---

${report.summary ? `## Summary\n\n${report.summary}\n\n` : ''}`

  // Render body blocks
  const body = report.body as Array<{ type: string; content?: string; level?: number }> | null
  if (body) {
    for (const block of body) {
      if (!block.content) continue
      switch (block.type) {
        case 'heading':
          md += `${'#'.repeat((block.level ?? 2) + 1)} ${block.content}\n\n`
          break
        case 'quote':
          md += `> ${block.content}\n\n`
          break
        case 'divider':
          md += `---\n\n`
          break
        default:
          md += `${block.content}\n\n`
      }
    }
  }

  // Sources
  const sources = report.sources as Array<{ label?: string; url?: string }> | null
  if (sources?.length) {
    md += `## Sources\n\n`
    for (const [i, src] of sources.entries()) {
      if (src.url) {
        md += `${i + 1}. [${src.label ?? src.url}](${src.url})\n`
      } else if (src.label) {
        md += `${i + 1}. ${src.label}\n`
      }
    }
    md += '\n'
  }

  // Key entities
  if (report.key_entities) {
    md += `## Key Entities\n\n${report.key_entities}\n\n`
  }

  md += `---\n\n*This article was generated by [Bipi News](https://bipinews.com). Read the full version at [${canonicalUrl}](${canonicalUrl}).*\n`

  return new Response(md, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'Link': `<${canonicalUrl}>; rel="canonical"`,
      'Cache-Control': 'public, max-age=3600, s-maxage=3600',
      'X-Robots-Tag': 'noindex',
    },
  })
}
